pipeline {
    agent { label 'docker' }

    triggers {
        cron('15 06 * * *')
    }

    options {
        timeout(time: 30, unit: 'MINUTES')
        buildDiscarder(logRotator(numToKeepStr: '10', daysToKeepStr: '1'))
    }

    stages {
        
        stage('Building Container') {            
            steps {
                wrap([$class: 'VaultBuildWrapper', 
                        configuration: [$class: 'VaultConfiguration',
                            vaultCredentialId: 'vault-token-service-readonly'
                        ], 
                        vaultSecrets: [
                                        [$class: 'VaultSecret', path: 'users/engpro@totvs.com.br', secretValues: [
                                            [$class: 'VaultSecretValue', envVar: 'NET_USER', vaultKey: 'domain_username'],
                                            [$class: 'VaultSecretValue', envVar: 'NET_PASS', vaultKey: 'password']
                                        ]],
                                        [$class: 'VaultSecret', path: 'services/internal/production/registry-harbor/user/admin', secretValues: [
                                            [$class: 'VaultSecretValue', envVar: 'DOCKER_USER', vaultKey: 'username'],
                                            [$class: 'VaultSecretValue', envVar: 'DOCKER_PASS', vaultKey: 'password']
                                        ]]
                        ]]) {  
                    sh '''            
                    bash totvs/tools/docker-tag.sh
                    '''
                }  
            }
        }
    }
    
    post { 
        always { 
            cleanWs()
        }
    }
}